services:
  solr:
    build:
      context: ${PROJECT_DIR}/docker-compose/solr
      dockerfile: Dockerfile

    image: "solr:${SOLR_VERSION}"
    container_name: ${SOLR_CONTAINER_NAME}
    # platform: ${DOCKER_PLATFORM}
    ports:
     - "8985:8983"
    volumes:
      - data:/var/solr
    # command:
    #   - solr-precreate
    #   - test
    restart: unless-stopped
